version: 2

jobs:
  prepare_common:
    machine: true
    steps:
      - run: |
          env
      - run: |
          mkdir -p ~/workspace/context
          cd ~/workspace/context
          echo "export COMMON=ready" >> build.env
          cat build.env
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - context

  prepare_commit:
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: |
          cd ~/workspace/context
          echo "export MODE=latest" >> build.env
          cat build.env
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - context

  prepare_tagged:
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: |
          cd ~/workspace/context
          echo "export MODE=tagged" >> build.env
          cat build.env
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - context

  prepare_cron:
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: |
          cd ~/workspace/context
          echo "export MODE=cron" >> build.env
          cat build.env
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - context

  build:
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: |
          cd ~/workspace/context
          source build.env
      - run: |
          env
      - run: |
          echo "done"

workflows:
  version: 2
  commit:
    jobs: &commit_jobs
      - prepare_common
      - prepare_commit:
          requires:
            - prepare_common
      - build:
          requires:
            - prepare_commit
  tag:
    jobs:
      - prepare_common:
          filters: &per_tag
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - prepare_commit:
          filters: *per_tag
          requires:
            - prepare_common
      - build:
          filters: *per_tag
          requires:
            - prepare_commit

  nightly:
    triggers:
      - schedule:
          cron: "20 * * * *"
          filters:
            branches:
              only:
                - master
    jobs: *commit_jobs
